function openv --description "1Password で .env の秘匿情報を管理する (op run 方式)"
    _ensure_commands_exist op; or return 1

    set -l subcmd $argv[1]

    switch "$subcmd"
        case run
            # -e <stage> を解析
            set -l stage ""
            set -l rest $argv[2..]
            if test (count $rest) -ge 2; and test "$rest[1]" = -e
                set stage $rest[2]
                set rest $rest[3..]
            end

            set -l env_file (_openv_env_file "$stage")
            if not test -f "$env_file"
                echo "$env_file が見つかりません。" >&2
                return 1
            end
            if test (count $rest) -lt 2; or test "$rest[1]" != --
                echo "使用法: openv run [-e <stage>] -- <command...>" >&2
                return 1
            end
            op run --env-file="$env_file" -- $rest[2..]

        case init
            # -e <stage> を解析
            set -l stage ""
            set -l source ""
            set -l i 2
            while test $i -le (count $argv)
                if test "$argv[$i]" = -e; and test (math $i + 1) -le (count $argv)
                    set stage $argv[(math $i + 1)]
                    set i (math $i + 2)
                else
                    set source $argv[$i]
                    set i (math $i + 1)
                end
            end

            # ソースファイル自動判定
            if test -z "$source"
                set source (_openv_source_file "$stage")
            end
            if not test -f "$source"
                echo "$source が見つかりません。" >&2
                return 1
            end

            set -l env_file (_openv_env_file "$stage")
            if test -f "$env_file"
                echo "$env_file は既に存在します。上書きしますか？ [y/N] " >&2
                read -l confirm
                if test "$confirm" != y; and test "$confirm" != Y
                    echo "中止しました。" >&2
                    return 1
                end
            end

            set -l item_name (_openv_item_name "$stage")
            set -l vault env

            echo "# Generated by openv init" >"$env_file"
            echo "# Vault: $vault / Item: $item_name" >>"$env_file"
            echo "" >>"$env_file"

            while read -l line
                if test -z "$line"; or string match -qr '^\s*#' "$line"
                    echo "$line" >>"$env_file"
                    continue
                end
                set -l key (string match -r '^([A-Za-z_][A-Za-z0-9_]*)=' "$line")[2]
                if test -n "$key"
                    set -l field_name (string lower "$key" | string replace -a '_' '-')
                    echo "$key=op://$vault/$item_name/$field_name" >>"$env_file"
                else
                    echo "# [openv:skip] $line" >>"$env_file"
                end
            end <"$source"

            echo "✔ $env_file を作成しました。" >&2

        case push
            # -e <stage> を解析
            set -l stage ""
            set -l source ""
            set -l i 2
            while test $i -le (count $argv)
                if test "$argv[$i]" = -e; and test (math $i + 1) -le (count $argv)
                    set stage $argv[(math $i + 1)]
                    set i (math $i + 2)
                else
                    set source $argv[$i]
                    set i (math $i + 1)
                end
            end

            # ソースファイル自動判定
            if test -z "$source"
                set source (_openv_source_file "$stage")
            end
            if not test -f "$source"
                echo "$source が見つかりません。" >&2
                return 1
            end

            set -l item_name (_openv_item_name "$stage")
            set -l env_file (_openv_env_file "$stage")
            set -l vault env

            # .env からキーと値を抽出
            set -l keys
            set -l values
            while read -l line
                if test -z "$line"; or string match -qr '^\s*#' "$line"
                    continue
                end
                set -l kv (string match -r '^([A-Za-z_][A-Za-z0-9_]*)=(.*)' "$line")
                if test -n "$kv"
                    set -a keys $kv[2]
                    set -a values $kv[3]
                end
            end <"$source"

            if test (count $keys) -eq 0
                echo "変数が見つかりません。" >&2
                return 1
            end

            echo "1Password に登録: vault=$vault, item=$item_name" >&2
            for i in (seq (count $keys))
                set -l field_name (string lower "$keys[$i]" | string replace -a '_' '-')
                printf "  %s → %s\n" $keys[$i] $field_name >&2
            end
            echo "" >&2
            echo "続行しますか？ [y/N] " >&2
            read -l confirm
            if test "$confirm" != y; and test "$confirm" != Y
                echo "中止しました。" >&2
                return 1
            end

            # 既存アイテムを確認
            set -l item_exists 0
            if op item get "$item_name" --vault "$vault" >/dev/null 2>&1
                set item_exists 1
            end

            # フィールド引数を組み立て
            set -l field_args
            for i in (seq (count $keys))
                set -l field_name (string lower "$keys[$i]" | string replace -a '_' '-')
                set -a field_args $field_name'[password]='$values[$i]
            end

            if test $item_exists -eq 1
                echo "既存アイテムを更新中..." >&2
                op item edit "$item_name" --vault "$vault" $field_args
            else
                echo "新規アイテムを作成中..." >&2
                op item create --vault "$vault" --title "$item_name" --category "Secure Note" $field_args
            end
            or begin
                echo "1Password への登録に失敗しました。" >&2
                return 1
            end

            echo "✔ 1Password に登録しました。" >&2

            # .env.op を生成
            echo "# Generated by openv push" >"$env_file"
            echo "# Vault: $vault / Item: $item_name" >>"$env_file"
            echo "" >>"$env_file"

            while read -l line
                if test -z "$line"; or string match -qr '^\s*#' "$line"
                    echo "$line" >>"$env_file"
                    continue
                end
                set -l key (string match -r '^([A-Za-z_][A-Za-z0-9_]*)=' "$line")[2]
                if test -n "$key"
                    set -l field_name (string lower "$key" | string replace -a '_' '-')
                    echo "$key=op://$vault/$item_name/$field_name" >>"$env_file"
                else
                    echo "# [openv:skip] $line" >>"$env_file"
                end
            end <"$source"

            echo "✔ $env_file を生成しました。" >&2
            echo "" >&2
            echo "元の $source は不要になりました。削除する場合:" >&2
            echo "  rm $source" >&2

        case show
            # -e <stage> を解析
            set -l stage ""
            if test (count $argv) -ge 3; and test "$argv[2]" = -e
                set stage $argv[3]
            end

            set -l env_file (_openv_env_file "$stage")
            if not test -f "$env_file"
                echo "$env_file が見つかりません。" >&2
                return 1
            end
            while read -l line
                set -l match (string match -r '^([A-Za-z_][A-Za-z0-9_]*)=(op://\S+)' "$line")
                if test -n "$match"
                    printf "%-30s → %s\n" $match[2] $match[3]
                end
            end <"$env_file"

        case help ''
            echo "openv - 1Password で .env の秘匿情報を管理 (op run 方式)" >&2
            echo "" >&2
            echo "使用法:" >&2
            echo "  openv push [-e <stage>] [file]  .env の値を 1Password に登録 + .env.op 生成" >&2
            echo "  openv init [-e <stage>] [file]  .env から .env.op テンプレートのみ生成" >&2
            echo "  openv run [-e <stage>] -- <cmd> .env.op の秘匿情報を注入してコマンド実行" >&2
            echo "  openv show [-e <stage>]         キーと参照先の一覧を表示" >&2
            echo "  openv help                      このヘルプを表示" >&2
            echo "" >&2
            echo "ステージ (-e) 指定時のファイル・アイテム対応:" >&2
            echo "  なし     .env    → .env.op             → op://env/<project>" >&2
            echo "  -e dev   .env.dev→ .env.dev.op         → op://env/<project>/dev" >&2
            echo "  -e stg   .env.stg→ .env.stg.op         → op://env/<project>/stg" >&2
            echo "  -e prod  .env.prod→ .env.prod.op       → op://env/<project>/prod" >&2
            echo "" >&2
            echo "秘匿情報はメモリ上でのみ展開され、ディスクに平文は残りません。" >&2
            echo ".env.op は op:// 参照のみなので git 管理可能です。" >&2

        case '*'
            echo "不明なサブコマンド: $subcmd" >&2
            echo "'openv help' でヘルプを表示" >&2
            return 1
    end
end

# --- ヘルパー関数 ---

function _openv_item_name --description "1Password アイテム名を返す"
    set -l project (basename (pwd))
    if set -q argv[1]; and test -n "$argv[1]"
        echo "$project/$argv[1]"
    else
        echo "$project"
    end
end

function _openv_env_file --description ".env.op ファイルパスを返す"
    if set -q argv[1]; and test -n "$argv[1]"
        echo ".env.$argv[1].op"
    else
        echo ".env.op"
    end
end

function _openv_source_file --description "ソース .env ファイルパスを返す"
    if set -q argv[1]; and test -n "$argv[1]"
        echo ".env.$argv[1]"
    else
        echo ".env"
    end
end
