[font]
normal = ["UDEV Gothic 35NFLG", "Symbols Nerd Font Mono"]
bold = ["UDEV Gothic 35NFLG", "Symbols Nerd Font Mono"]
italic = ["UDEV Gothic 35NFLG", "Symbols Nerd Font Mono"]
bold_italic = ["UDEV Gothic 35NFLG", "Symbols Nerd Font Mono"]
size = 12.0
