gui:
  showIcons: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: "<c-r>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
