gui:
  showIcons: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: "<c-r>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"

os:
  open: 'nvim --server "$HOME/.nvim-server.sock" --remote-send "<C-\><C-N>:execute \"lua Snacks.lazygit() \" | e {{filename}}<CR>"'
