[tools]
bat = "latest"
bun = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
lazygit = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
rust = "nightly"
starship = "latest"
tmux = "latest"
usage = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
