[tools]
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"
